// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlMsgBody } from "./ControlMsgBody";

export type ControlMsg = { id: number, body: ControlMsgBody, };
