// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlResBody } from "./ControlResBody";

export type ControlResMsg = { id: number, body: ControlResBody, };
