// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartVideoMsg } from "./StartVideoMsg";

export type ControlMsg = "Empty" | { "StartVideo": StartVideoMsg };
